# Generated by Django 4.2.6 on 2023-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_tbl',
            name='ps2',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
