# Generated by Django 4.2.6 on 2023-12-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_contact_delete_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Payment_status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
